name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
    paths:
      - '**/*'  # Deploy all files (you can customize this pattern)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use your GitHub secret for AWS access key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use your GitHub secret for AWS secret key
          aws-region: 'us-east-1'  # You can specify the region of your S3 bucket

      - name: Deploy updated files to S3
        run: |
          # Check if the repository has previous commits
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            # If a previous commit exists, get the changed files since the last commit
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD --)
          else
            # If no previous commit, consider all files as new files
            CHANGED_FILES=$(git ls-files)
          fi
          
          # If any files were changed, upload them to S3
          for FILE in $CHANGED_FILES; do
            # Make sure we're not trying to upload files from .git directory or other ignored files
            if [[ "$FILE" != .git/* ]]; then
              echo "Deploying $FILE to S3"
              aws s3 cp "$FILE" s3://w3storagemaplegrove/"$FILE" --acl public-read --exact-timestamps
            fi
          done
